### ISSUE TITLE
Home Assistant 升级到core-2021.6.1后报错

### ISSUE THREAD

**Issue by fkueyu** [shaonianzhentan/ha_baidu_map#19]
版本 | core-2021.6.1
前端版本： 20210603.0 - latest

错误日志：

Logger: homeassistant.components.websocket_api.http.connection
Source: components/homeassistant/__init__.py:161
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 09:33:18 (2 occurrences)
Last logged: 09:38:33

[140673840394144] The system cannot restart because the configuration is not valid: Component error: ha_baidu_map - Integration 'ha_baidu_map' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 728, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 161, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Component error: ha_baidu_map - Integration 'ha_baidu_map' not found.

**Comment by fkueyu** [comment]
manifest.json文件加上：   "version": "2.4"
已解决
